import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Navbar from "./ui/navbar";
import Footer from "./ui/footer";
import { CartProvider } from '@/app/context/cartContext'


const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Audiophile ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CartProvider>
      <body className={manrope.variable}>
        <Navbar />
        {children}
        <footer>
          <Footer />
        </footer>
      </body>
    </CartProvider>
    </html>
  );
}
